# Generated by Django 5.1.6 on 2025-02-14 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=55)),
                ('model', models.CharField(max_length=55)),
                ('year', models.CharField(max_length=4)),
                ('color', models.CharField(max_length=55)),
                ('image', models.ImageField(upload_to='Car_Profile')),
                ('plate_number', models.CharField(max_length=10)),
                ('available', models.BooleanField(default=True)),
                ('millage', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaseapp.enginetype')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaseapp.vehicletype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeasePrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('weekly_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaseapp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duration_type', models.CharField(choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month')], default='Day', max_length=10)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user_ip', models.GenericIPAddressField()),
                ('profile_image', models.ImageField(upload_to='Client_photo')),
                ('phone_number_1', models.CharField(max_length=15)),
                ('phone_number_2', models.CharField(blank=True, max_length=15, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('aggreement', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaseapp.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
